### ISSUE TITLE
Svårt med gemensam initialize

### ISSUE THREAD

**Issue by itggot-daniel-berg** [itggot-simon-johannesson/webbserverprojekt_imdb#10]
Det går, men jag föreslår du avvaktar tills du är klar med resten

https://github.com/itggot-simon-johannesson/webbserverprojekt_imdb/blob/a95cb7140dc30517062130d013916c5811f07dd0/models/baseclass.rb#L3-L12

**Comment by simon-ulrik** [comment]
tror den funkar

**Comment by ntijoh-daniel-berg** [comment]
Ja, men bara för du skriver över den i alla klasser förutom user. I så fall föreslår jag du flyttar den till user istället.
