### ISSUE TITLE
Spana in sinatra before-filter

### ISSUE THREAD

**Issue by itggot-daniel-berg** [itggot-simon-johannesson/webbserverprojekt_imdb#2]
https://github.com/itggot-simon-johannesson/webbserverprojekt_imdb/blob/a95cb7140dc30517062130d013916c5811f07dd0/imdb.rb#L10-L12

**Comment by itggot-daniel-berg** [comment]
https://github.com/itggot-simon-johannesson/webbserverprojekt_imdb/blob/a95cb7140dc30517062130d013916c5811f07dd0/imdb.rb#L43-L46

**Comment by itggot-simon-johannesson** [comment]
done

**Comment by itggot-simon-johannesson** [comment]
det va inget
