### ISSUE TITLE
what if it fails?

### ISSUE THREAD

**Issue by itggot-daniel-berg** [itggot-simon-johannesson/webbserverprojekt_imdb#4]
https://github.com/itggot-simon-johannesson/webbserverprojekt_imdb/blob/a95cb7140dc30517062130d013916c5811f07dd0/imdb.rb#L21-L24

**Comment by itggot-simon-johannesson** [comment]
Då skickas man till "/". Det går inte att lägga till tomma användare.

**Comment by itggot-daniel-berg** [comment]
Jag tänkte det kunde vara intressant för den som försökte skapa ett konto att få reda på att kontot faktiskt inte skapades...
